# Generated by Django 4.2.6 on 2023-10-09 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_cart_updated'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='live_cart',
            field=models.OneToOneField(blank=True, help_text="Customer's live cart that will get deleted/emptied when order is successful.", null=True, on_delete=django.db.models.deletion.SET_NULL, to='cart.cart'),
        ),
        migrations.AlterField(
            model_name='order',
            name='cart',
            field=models.OneToOneField(help_text='The exact items customer is paying for, frozen in time, so records exist even if products get removed from site.', on_delete=django.db.models.deletion.PROTECT, to='orders.frozencart'),
        ),
    ]
