# Generated by Django 4.2.4 on 2023-09-03 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("description", models.TextField()),
                ("slug", models.SlugField(help_text="Must be unique.", unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="ProductType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="General Product Type, eg. tea, teaware, scarves (lol) etc.",
                        max_length=150,
                    ),
                ),
                ("description", models.TextField()),
                ("slug", models.SlugField(help_text="Must be unique.", unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("description", models.TextField()),
                ("is_published", models.BooleanField(default=False)),
                ("quantity", models.PositiveIntegerField()),
                ("slug", models.SlugField(help_text="Must be unique.", unique=True)),
                ("categories", models.ManyToManyField(to="products.category")),
                (
                    "product_type",
                    models.ForeignKey(
                        help_text="General Product Type, eg. tea, teaware, scarves (lol) etc.",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="products.producttype",
                    ),
                ),
            ],
        ),
    ]
