# Generated by Django 4.2.5 on 2023-09-10 04:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="cartitem",
            constraint=models.UniqueConstraint(
                fields=("cart", "product"),
                name="One unique product per cart",
                violation_error_message="There can't be more than one of the same product in a cart, add quantity instead.",
            ),
        ),
    ]
