# Generated by Django 4.2.5 on 2023-09-18 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0002_cartitem_one_unique_product_per_cart"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="cartitem",
            constraint=models.CheckConstraint(
                check=models.Q(("quantity__gt", 0)),
                name="Quantity can't be 0",
                violation_error_message="Cart item quantity can't be 0 or less, use delete instead.",
            ),
        ),
    ]
