# Generated by Django 5.0 on 2024-01-04 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0003_alter_post_body_featuredpost"),
        ("wagtailimages", "0025_alter_image_file_alter_rendition_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="featuredpost",
            name="preview_image",
            field=models.ForeignKey(
                blank=True,
                help_text="This image can be different from any images in the post.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
    ]
