# Generated by Django 5.0 on 2024-01-14 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_alter_post_body_featuredpost'),
        ('content', '0004_receipespage'),
    ]

    operations = [
    ]
