# Generated by Django 5.0 on 2024-01-14 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_alter_featuredpost_preview_image'),
        ('content', '0005_merge_20240114_1550'),
    ]

    operations = [
    ]
